project:
  type: website

website:
  title: "SAGE Tutorial Guide"
  description: "A comprehensive guide for using SAGE"
  
  sidebar:
    style: "docked"
    background: light
    contents:
      - g_started.qmd
      - c_room.qmd
      - upload_download.qmd
      - int_app.qmd
      - f_user.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 3
    code-fold: false
    number-sections: true

execute:
  freeze: auto
